-- V1: HDFC Life 3NF schema (H2 MODE=PostgreSQL + PostgreSQL)

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    CONSTRAINT uk_customers_full_name UNIQUE (full_name),
    CONSTRAINT uk_customers_email UNIQUE (email)
);

CREATE TABLE policies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no     VARCHAR(64) NOT NULL,
    customer_id   BIGINT NOT NULL,
    product_type  VARCHAR(32) NOT NULL,
    base_premium  INTEGER NOT NULL,
    status        VARCHAR(32) NOT NULL,
    CONSTRAINT uk_policies_policy_no UNIQUE (policy_no),
    CONSTRAINT fk_policies_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_policies_product_type CHECK (product_type IN ('TERM', 'ULIP', 'ENDOWMENT')),
    CONSTRAINT chk_policies_base_premium CHECK (base_premium > 0),
    CONSTRAINT chk_policies_status CHECK (status IN ('Active', 'Lapsed', 'Pending'))
);

CREATE TABLE claims (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_no   VARCHAR(64) NOT NULL,
    policy_id  BIGINT NOT NULL,
    amount     INTEGER NOT NULL,
    urgency    VARCHAR(16) NOT NULL,
    status     VARCHAR(32) NOT NULL,
    CONSTRAINT uk_claims_claim_no UNIQUE (claim_no),
    CONSTRAINT fk_claims_policy FOREIGN KEY (policy_id) REFERENCES policies (id),
    CONSTRAINT chk_claims_amount CHECK (amount > 0),
    CONSTRAINT chk_claims_urgency CHECK (urgency IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT chk_claims_status CHECK (status IN ('SUBMITTED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE riders (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  VARCHAR(64) NOT NULL,
    name  VARCHAR(255) NOT NULL,
    CONSTRAINT uk_riders_code UNIQUE (code)
);

CREATE TABLE policy_riders (
    policy_id  BIGINT NOT NULL,
    rider_id   BIGINT NOT NULL,
    CONSTRAINT pk_policy_riders PRIMARY KEY (policy_id, rider_id),
    CONSTRAINT fk_policy_riders_policy FOREIGN KEY (policy_id) REFERENCES policies (id),
    CONSTRAINT fk_policy_riders_rider FOREIGN KEY (rider_id) REFERENCES riders (id)
);
